# 1.Pandas -Basics

- Dataframe - SPecial Object to Data in Tabular Form (Rows & Column)

In [1]:
import numpy as np
import pandas as pd

In [8]:
#lowerbound - 1
#Upperbound - 100
#NUmber of Entries to Generate - 10
np.random.randint(1,100,10)

array([73, 51, 66,  8, 15, 74, 91, 99, 61, 44])

In [9]:
#Try to create a data frame
user_data = {
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(1,100,5),
}

In [10]:
user_data

{'MarksA': array([56, 50, 88, 61, 73]),
 'MarksB': array([57, 57, 74, 51, 79]),
 'MarksC': array([11, 89, 45, 49,  6])}

In [11]:
#To create table
df = pd.DataFrame(user_data)
print(df)

   MarksA  MarksB  MarksC
0      56      57      11
1      50      57      89
2      88      74      45
3      61      51      49
4      73      79       6


In [12]:
#To create table another way
df.head()

MarksA  MarksB  MarksC
0      56      57      11
1      50      57      89
2      88      74      45
3      61      51      49
4      73      79       6

In [13]:
#To see headings of columns
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [14]:
#To see first 3 rows
df.head(n=3)

MarksA  MarksB  MarksC
0      56      57      11
1      50      57      89
2      88      74      45

In [19]:
#Convert integers datatype into float32
df = pd.DataFrame(user_data,dtype='float32')
print(df)

   MarksA  MarksB  MarksC
0    56.0    57.0    11.0
1    50.0    57.0    89.0
2    88.0    74.0    45.0
3    61.0    51.0    49.0
4    73.0    79.0     6.0


In [20]:
#To create CSV from dataframe
df.to_csv('marks.csv')

In [30]:
my_data = pd.read_csv('marks.csv')
my_data   # you can directly say to print without using print word

Unnamed: 0  MarksA  MarksB  MarksC
0           0    56.0    57.0    11.0
1           1    50.0    57.0    89.0
2           2    88.0    74.0    45.0
3           3    61.0    51.0    49.0
4           4    73.0    79.0     6.0

In [31]:
#Suppose you want to remove any column from above table mentioned
my_data = pd.read_csv('marks.csv')
my_data = my_data.drop(columns=['Unnamed: 0'])
my_data # you can directly say to print without using print word

MarksA  MarksB  MarksC
0    56.0    57.0    11.0
1    50.0    57.0    89.0
2    88.0    74.0    45.0
3    61.0    51.0    49.0
4    73.0    79.0     6.0

# 2.Pandas - Basics

In [32]:
my_data.describe()

MarksA     MarksB     MarksC
count   5.0000   5.000000   5.000000
mean   65.6000  63.600000  40.000000
std    15.1096  12.157302  33.555923
min    50.0000  51.000000   6.000000
25%    56.0000  57.000000  11.000000
50%    61.0000  57.000000  45.000000
75%    73.0000  74.000000  49.000000
max    88.0000  79.000000  89.000000

In [33]:
#To access last three rows of table
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    88.0    74.0    45.0
3    61.0    51.0    49.0
4    73.0    79.0     6.0

In [34]:
#To access particular row
df.iloc[3] #i.e. 3rd row

MarksA    61.0
MarksB    51.0
MarksC    49.0
Name: 3, dtype: float32

In [35]:
# To access both particular row and column
df.iloc[3,1] #i.e. 3rd row, index 1

51.0

In [38]:
#At what index particular column is
idx = df.columns.get_loc('MarksB')
df.iloc[3,idx]

51.0

In [39]:
#To read both columns of B and C
idx = [df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(idx)
df.iloc[3,idx]

[1, 2]


MarksB    51.0
MarksC    49.0
Name: 3, dtype: float32

In [40]:
#Slicing
df.iloc[:3,idx]

MarksB  MarksC
0    57.0    11.0
1    57.0    89.0
2    74.0    45.0

In [41]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0    57.0    11.0
1    57.0    89.0
2    74.0    45.0

In [48]:
# Sort your dataframe
my_data

MarksA  MarksB  MarksC
0    56.0    57.0    11.0
1    50.0    57.0    89.0
2    88.0    74.0    45.0
3    61.0    51.0    49.0
4    73.0    79.0     6.0

In [55]:
my_data.sort_values(by=["MarksC","MarksA"],ascending=False)

MarksA  MarksB  MarksC
1    50.0    57.0    89.0
3    61.0    51.0    49.0
2    88.0    74.0    45.0
0    56.0    57.0    11.0
4    73.0    79.0     6.0

In [56]:
data_array = my_data.values

In [57]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [58]:
print(data_array)

[[56. 57. 11.]
 [50. 57. 89.]
 [88. 74. 45.]
 [61. 51. 49.]
 [73. 79.  6.]]


In [59]:
print(type(data_array))

<class 'numpy.ndarray'>


In [61]:
data_array.shape

(5, 3)

In [62]:
data_array[2][2]

45.0

In [63]:
#Numpy arrays back into dataframe
new_df = pd.DataFrame(data_array,dtype='int32',columns=["Physics","Chem","Maths"])

In [64]:
new_df

Physics  Chem  Maths
0       56    57     11
1       50    57     89
2       88    74     45
3       61    51     49
4       73    79      6

In [66]:
new_df.to_csv("PCM.csv",index=False)

In [67]:
pcm = pd.read_csv('PCM.csv')

In [68]:
print(pcm)

   Physics  Chem  Maths
0       56    57     11
1       50    57     89
2       88    74     45
3       61    51     49
4       73    79      6


# LOding & Visualising MNIST Dataset using Pandas & Matplotlib

In [69]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#df = pd.read_csv("../Datasets/MNIST-2/minst_train.csv") -- this datset is not in directory so i have just followed up steps below.
#df.shape
#df.head(n=3)
#print(type(df))
#data = df.values
#print(data)
#print(data.shape)
#X = data[ : ,1: ]
#Y = data[ : ,0]
#print(X.shape,Y.shape)

##Try to visualise one image
#X[0].shape

#def drawImg(X,Y,i):
#     plt.imshow(X[i].reshape(28,28),cmap='gray')
#     plt.title("Label "+ str(Y[i]))
#     plt.show()
#     
#for i in range(1)        
#     drawImg(X,Y,i)

##Split this dataset
#split = int(0.80*X.shape[0])
#print(split)

#X_train,Y_train = X[split, :], Y[:split]
#X_test,Y_test = X[split: , :], Y[split: ]

#print(X_train.shape,Y_train.shape)
#print(X_test.shape,Y_test.shape)

#Randomization
#import numpy as np
#a = np.array([1,2,3,4,5])
#np.random.shuffle(a)
#print(a)

#Randomly shuffle a 2D array
#a = np.array([1,2,3],
#            [4,5,6],
#            [7,8,9])
#np.random.shuffle(a)
#print(a)

# Try to plot a visualisation (Grid of first 25 images 5 X 5)
# plt.figure(figsize=(10,10))
# for i in range(25):
#     plt.subplot(5,5,i+1)
#     plt.imshow(X_train[i].reshape(28,28),cmap='gray')
#     plt.title(Y_train[i])
#     plt.axis("off")

